INSERT INTO COURSE(COURSE_DESC) VALUES('IT');
INSERT INTO COURSE(COURSE_DESC) VALUES('ESD');

INSERT INTO INTEREST(INTEREST_DESC) VALUES('Coding');
INSERT INTO INTEREST(INTEREST_DESC) VALUES('Singing');
INSERT INTO INTEREST(INTEREST_DESC) VALUES('Dancing');
INSERT INTO INTEREST(INTEREST_DESC) VALUES('Internet Surfing');

