--CREATE DATABASE IIITBSOCIALNETWORK;

USE IIITBSOCIALNETWORK;

DROP TABLE USER_PROF_DETAILS;

DROP TABLE USER_FRND_MAP;

DROP TABLE USER_POST_DETAILS;

DROP TABLE USER_INTERESTS;

DROP TABLE USER_LOGIN;

DROP TABLE USER_ID_MAP;

DROP TABLE COURSE;

DROP TABLE INTEREST;

DROP USER 'IIITBJAVA'@'localhost';


CREATE TABLE INTEREST ( INTEREST_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,  INTEREST_DESC VARCHAR(100),PRIMARY KEY (INTEREST_ID));

CREATE TABLE COURSE (  COURSE_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, COURSE_DESC VARCHAR(100) , PRIMARY KEY(COURSE_ID));


CREATE TABLE USER_ID_MAP ( USER_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT, ROLL_NO VARCHAR(9) UNIQUE, EMAILID VARCHAR(100) UNIQUE,PRIMARY KEY (USER_ID));

CREATE TABLE USER_LOGIN (USER_ID INTEGER UNSIGNED,PASSWORD VARCHAR(10),PRIMARY KEY (USER_ID),FOREIGN KEY(USER_ID) REFERENCES USER_ID_MAP(USER_ID)); 

CREATE TABLE USER_INTERESTS (  USER_ID INTEGER UNSIGNED NOT NULL ,  INTEREST_ID INTEGER ,PRIMARY KEY (USER_ID), FOREIGN KEY (USER_ID) REFERENCES USER_ID_MAP(USER_ID));  

CREATE TABLE USER_POST_DETAILS ( USER_ID INTEGER UNSIGNED NOT NULL,POST_CONTENT VARCHAR(255), POST_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (USER_ID) REFERENCES USER_ID_MAP(USER_ID));

CREATE TABLE USER_FRND_MAP( USER_ID INTEGER UNSIGNED NOT NULL , FRND_ID INTEGER UNSIGNED NOT NULL,PRIMARY KEY (USER_ID), FOREIGN KEY (USER_ID) REFERENCES USER_ID_MAP(USER_ID),FOREIGN KEY (FRND_ID) REFERENCES USER_ID_MAP(USER_ID));

CREATE TABLE USER_PROF_DETAILS ( USER_ID INTEGER UNSIGNED NOT NULL,  USER_NAME VARCHAR(100), PROFILE_PIC LONGBLOB, GENDER VARCHAR(1),COURSE_ID INTEGER UNSIGNED NOT NULL, PHONE_NO VARCHAR(10),PRIMARY KEY (USER_ID), FOREIGN KEY (USER_ID) REFERENCES USER_ID_MAP(USER_ID),FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)); 

CREATE USER 'IIITBJAVA'@'localhost' IDENTIFIED BY 'IIITBJAVA';

GRANT ALL ON IIITBSOCIALNETWORK TO 'IIITBJAVA'@'localhost';

FLUSH PRIVILEGES;

